# Generated by Django 4.0.5 on 2022-11-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='bee_level',
            field=models.CharField(choices=[('Level_1', 'Level 1'), ('Level_2', 'Level 2'), ('Level_3', 'Level 3'), ('Level_4', 'Level 4'), ('Level_5', 'Level 5'), ('Level_6', 'Level 6'), ('Level_7', 'Level 7'), ('Level_8', 'Level 8'), ('None', 'None')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='province',
            field=models.CharField(choices=[('Gauteng', 'Gauteng'), ('Mpumalanga', 'Mpumalanga'), ('KZN', 'KZN'), ('KZN', 'KZN'), ('KZN', 'KZN'), ('North_West', 'North West'), ('Limpopo', 'Limpopo'), ('Western_Cape', 'Western Cape'), ('Free_State', 'Free State'), ('Eastern_Cape', 'Eastern Cape'), ('Northern_Cape', 'Northern Cape')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Disbursments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disbursement_code', models.CharField(max_length=255, null=True)),
                ('disbursement_description', models.CharField(max_length=255, null=True)),
                ('disbursement_application_id', models.CharField(max_length=255, null=True)),
                ('disbursement_reason', models.CharField(max_length=255, null=True)),
                ('disbursement_type', models.CharField(choices=[('Loan', 'Loan'), ('Grant', 'Grant')], max_length=10)),
                ('disbursement_date', models.DateField(null=True)),
                ('disbursement_amount', models.FloatField(default=0)),
                ('contract_signed_date', models.DateField(null=True)),
                ('disbursement_allotment', models.CharField(choices=[('First_Allotment', 'First Allotment'), ('Second_Allotment', 'Second Allotment'), ('Third_Allotment', 'Third Allotment')], max_length=64)),
                ('disbursement_interest_rate', models.FloatField(default=0)),
                ('repayment_term', models.IntegerField(blank=True)),
                ('total_target', models.FloatField(default=0)),
                ('monthly_target', models.FloatField(default=0)),
                ('target_measurement_unit', models.CharField(default='Tone', max_length=64)),
                ('application_contract_document', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.customers')),
            ],
        ),
    ]
