# Generated by Django 4.0.5 on 2022-11-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0002_customers_bee_level_customers_city_customers_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disbursments',
            new_name='Disbursements',
        ),
    ]
