# Generated by Django 4.0.5 on 2022-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0003_rename_disbursments_disbursements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='bee_level',
            field=models.CharField(blank=True, choices=[('Level_1', 'Level 1'), ('Level_2', 'Level 2'), ('Level_3', 'Level 3'), ('Level_4', 'Level 4'), ('Level_5', 'Level 5'), ('Level_6', 'Level 6'), ('Level_7', 'Level 7'), ('Level_8', 'Level 8'), ('None', 'None')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='province',
            field=models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Mpumalanga', 'Mpumalanga'), ('KZN', 'KZN'), ('KZN', 'KZN'), ('KZN', 'KZN'), ('North_West', 'North West'), ('Limpopo', 'Limpopo'), ('Western_Cape', 'Western Cape'), ('Free_State', 'Free State'), ('Eastern_Cape', 'Eastern Cape'), ('Northern_Cape', 'Northern Cape')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_application_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
