# Generated by Django 4.0.5 on 2022-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0004_alter_customers_bee_level_alter_customers_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contact_person',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
