# Generated by Django 4.0.5 on 2022-11-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0005_customers_contact_person_customers_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Contract_Complete', 'Contract Complete'), ('Business_Closed', 'Business Closed'), ('Other', 'Other')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='disbursements',
            name='disbursement_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Repayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('Monthly_Repayment', 'Monthly Repayment'), ('Impairment', 'Impairment'), ('Other', 'Other')], max_length=64)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('actual_tonnage', models.FloatField(blank=True, null=True)),
                ('payment_documentation', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.customers')),
            ],
        ),
    ]
