# Generated by Django 4.0.5 on 2022-11-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0006_customers_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayments',
            name='disbursement_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.disbursements'),
        ),
    ]
