# Generated by Django 4.0.5 on 2022-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0007_repayments_disbursement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayments',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
