# Generated by Django 4.0.5 on 2022-11-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0008_repayments_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_management_app.customers'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_management_app.customers'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='disbursement_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_management_app.disbursements'),
        ),
    ]
