# Generated by Django 4.0.5 on 2022-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0009_alter_disbursements_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_type',
            field=models.CharField(choices=[('Collector', 'Collector'), ('Recycler', 'Recycler'), ('Quality', 'Quality')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
