# Generated by Django 4.0.5 on 2022-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0010_customers_customer_type_alter_customers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
