# Generated by Django 4.0.5 on 2022-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0011_customers_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
