# Generated by Django 4.0.5 on 2022-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0014_alter_customers_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='application_contract_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='contract_signed_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_end',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='actual_tonnage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
