# Generated by Django 4.0.5 on 2022-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0015_alter_disbursements_application_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='contract_signed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_end',
            field=models.DateField(null=True),
        ),
    ]
