# Generated by Django 4.0.5 on 2022-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0016_alter_disbursements_contract_signed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
