# Generated by Django 4.0.5 on 2022-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0017_alter_disbursements_contract_signed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='total_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
