# Generated by Django 4.0.5 on 2022-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0022_alter_disbursements_monthly_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='total_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
