# Generated by Django 4.0.5 on 2022-12-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0023_alter_disbursements_monthly_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='province',
            field=models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Mpumalanga', 'Mpumalanga'), ('KZN', 'KZN'), ('North_West', 'North West'), ('Limpopo', 'Limpopo'), ('Western_Cape', 'Western Cape'), ('Free_State', 'Free State'), ('Eastern_Cape', 'Eastern Cape'), ('Northern_Cape', 'Northern Cape')], max_length=64, null=True),
        ),
    ]
