# Generated by Django 4.0.5 on 2022-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0024_alter_customers_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
