# Generated by Django 4.0.5 on 2022-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0025_customers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursements',
            name='disbursement_monthly_repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
