# Generated by Django 4.0.5 on 2022-12-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0026_disbursements_disbursement_monthly_repayment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayments',
            old_name='actual_tonnage',
            new_name='actual_volume_tone',
        ),
        migrations.RenameField(
            model_name='repayments',
            old_name='payment_amount',
            new_name='repayment_amount',
        ),
        migrations.RenameField(
            model_name='repayments',
            old_name='payment_date',
            new_name='repayment_date',
        ),
        migrations.RenameField(
            model_name='repayments',
            old_name='payment_description',
            new_name='repayment_description',
        ),
        migrations.RenameField(
            model_name='repayments',
            old_name='payment_type',
            new_name='repayment_type',
        ),
        migrations.RemoveField(
            model_name='repayments',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='repayments',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='repayments',
            name='payment_reason',
        ),
        migrations.AddField(
            model_name='repayments',
            name='repayment_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
