# Generated by Django 4.0.5 on 2022-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0028_rename_repayment_id_repayments_repayment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_monthly_repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
