# Generated by Django 4.0.5 on 2022-12-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0029_alter_disbursements_disbursement_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='repayment_type',
            field=models.CharField(choices=[('Monthly_Repayment', 'Monthly Repayment'), ('Interest', 'Interest'), ('Other', 'Other')], max_length=64),
        ),
        migrations.CreateModel(
            name='GrantManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_volume_report_id', models.IntegerField(blank=True)),
                ('volume_report_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=64)),
                ('volume_report_year', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044'), ('2045', '2045'), ('2046', '2046'), ('2047', '2047'), ('2048', '2048'), ('2049', '2049'), ('2050', '2050')], max_length=64)),
                ('hd_kg', models.IntegerField(blank=True)),
                ('ld_kg', models.IntegerField(blank=True)),
                ('lld_kg', models.IntegerField(blank=True)),
                ('pp_kg', models.IntegerField(blank=True)),
                ('pvc_kg', models.IntegerField(blank=True)),
                ('ps_kg', models.IntegerField(blank=True)),
                ('pet_kg', models.IntegerField(blank=True)),
                ('other_kg', models.IntegerField(blank=True)),
                ('total_volume_kg', models.IntegerField(blank=True)),
                ('volume_report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_management_app.customers')),
                ('disbursement_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_management_app.disbursements')),
            ],
        ),
    ]
