# Generated by Django 4.0.5 on 2022-12-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0030_alter_repayments_repayment_type_grantmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmanagement',
            name='amount_amortized',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grantmanagement',
            name='amount_impaired',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
