# Generated by Django 4.0.5 on 2023-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0031_grantmanagement_amount_amortized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantmanagement',
            name='monthly_volume_report_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
