# Generated by Django 4.0.5 on 2023-01-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management_app', '0033_remove_repayments_repayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursements',
            name='contract_monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='disbursements',
            name='contract_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
